#!/bin/bash
git status|grep -v "gen"|grep 'modified:'|grep "\.go"|awk '{print $2}'|xargs -L 1 ${GOF_BIN}
git status|grep -v "gen"|grep 'new file:'|grep "\.go"|awk -F '   ' '{print $2}'|xargs -L 1 ${GOF_BIN}
git status|grep -v "gen"|grep 'renamed:'|grep "\.go"|awk '{print $4}'|xargs -L 1 ${GOF_BIN}
git status|grep -v "gen"|grep "\.go"|grep -v 'modified:'|grep -v 'new file:'|grep -v "renamed:"|grep -v "deleted:"|xargs -L 1 ${GOF_BIN}
